#![no_std]
// `create_award` legitimately carries a full award definition as explicit
// parameters; the lint fires on the code generated by the contract macros.
#![allow(clippy::too_many_arguments)]

//! Scholarship/bursary award lifecycle contract.
//!
//! Scope of this pass (issues #1090, #1091, #1092):
//!
//! - **#1090 — Create award records and acceptance deadlines.** An admin
//!   materializes an approved award with its amount, currency, immutable
//!   terms reference, optional milestone-schedule reference, and an
//!   expiring acceptance window. A single `(recipient, program_id)`
//!   uniqueness key means an applicant cannot hold conflicting awards,
//!   and every decline/expiry/cancellation/termination releases the
//!   award's budget reservation.
//! - **#1091 — Capture signed award agreement acceptance.** `accept_award`
//!   records the recipient's own signature over the *exact* award terms
//!   (version + integrity hash), a verifiable signer address, a ledger
//!   timestamp, and an integrity commitment to the required declarations.
//!   Versions are immutable; a declined or expired offer can never
//!   disburse.
//! - **#1092 — Handle award cancellation and termination.** A single
//!   policy-valid transition table gates every status change. Pre-payment
//!   cancellation (`cancel_award`) and post-payment termination
//!   (`terminate_award`) stop all future disbursements, record the reason
//!   and authority, and track any recovery in a dedicated record separate
//!   from the amount already paid.
//!
//! On-chain storage is privacy-minimized: award terms and declarations are
//! never stored — only caller-supplied `BytesN<32>` integrity commitments
//! over the off-chain documents, plus metadata required to enforce the
//! lifecycle. See `contracts/docs/scholarship-awards.md` for ownership,
//! privacy, migration, and operational notes.
//!
//! Actually moving funds is **not** implemented here (see ADR 0002's
//! disbursement non-goal): `record_disbursement` records that a payment
//! happened elsewhere so that #1092 can distinguish pre-payment
//! cancellation from post-payment termination. Wiring real token transfers
//! in is follow-up work.

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, Address, BytesN, Env, Symbol,
};

const CONTRACT_VERSION: u32 = 1;

// TTL constants: ~1 year at 6-second ledgers, matching the sibling
// scholarship contracts' convention.
const RECORD_MIN_TTL: u32 = 3_110_400;
const RECORD_MAX_TTL: u32 = 6_220_800;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ContractError {
    NotInitialized = 1,
    AlreadyInitialized = 2,
    NotAdmin = 3,
    AwardNotFound = 4,
    /// #1090 — an award with this ID already exists; identifiers never change.
    AwardAlreadyExists = 5,
    /// #1090 — the award amount must be strictly positive.
    InvalidAmount = 6,
    /// #1090 — the acceptance deadline must be strictly in the future.
    InvalidDeadline = 7,
    /// #1090 — the recipient already holds an active award for this program.
    ConflictingAward = 8,
    /// #1091 — the caller is not the award's recipient.
    NotRecipient = 9,
    /// #1091/#1092 — the action is not permitted from the award's current status.
    OfferNotActive = 10,
    /// #1091 — the acceptance window has already closed.
    OfferExpired = 11,
    /// #1092 — the requested status change is not a legal transition.
    InvalidTransition = 12,
    /// #1092 — pre-payment cancellation is not allowed once funds were paid.
    PaymentAlreadyMade = 13,
    /// #1092 — post-payment termination requires at least one recorded disbursement.
    NoPaymentMade = 14,
    /// #1092 — the recovery amount exceeds what was actually paid out.
    RecoveryExceedsPaid = 15,
    /// A disbursement would push the paid total past the award amount.
    DisbursementExceedsAward = 16,
    /// Reservation accounting underflow — no reservation to release.
    NoReservation = 17,
    /// Disbursement attempted on an award that is not in the `Accepted` state.
    AwardNotDisburseable = 18,
    /// #1090 — `expire_award` was called before the acceptance deadline.
    OfferNotExpired = 19,
    /// #1091 — no acceptance has been captured for this award yet.
    AcceptanceNotFound = 20,
}

#[contracttype]
#[derive(Clone)]
pub enum DataKey {
    Admin,
    /// #1090 — an award record, keyed by its stable award ID.
    Award(BytesN<32>),
    /// #1090 — the one active award for a `(recipient, program_id)` pair.
    /// Presence of this key is the "conflicting awards" guard.
    ActiveAward(Address, BytesN<32>),
    /// #1091 — the signed acceptance captured for a given award.
    Acceptance(BytesN<32>),
    /// #1092 — the recovery tracked for a terminated award, kept separate
    /// from the amount already paid.
    Recovery(BytesN<32>),
    /// #1090 — count of awards currently holding a reservation per program.
    Reservation(BytesN<32>),
}

/// #1090/#1091/#1092 — the explicit award lifecycle. Only transitions
/// enumerated in `is_legal_transition` succeed; every other pair is
/// rejected with `InvalidTransition`.
#[contracttype]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AwardStatus {
    /// Materialized, awaiting the recipient's signed acceptance or decline.
    Offered,
    /// The recipient signed the agreement; disbursements may now occur.
    Accepted,
    /// The recipient declined; terminal, and cannot disburse.
    Declined,
    /// The acceptance window elapsed without a decision; terminal.
    Expired,
    /// Cancelled before any payment; terminal, and cannot disburse.
    Cancelled,
    /// Terminated after at least one payment; terminal, and cannot disburse.
    Terminated,
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Award {
    pub id: BytesN<32>,
    pub program_id: BytesN<32>,
    pub recipient: Address,
    /// Principal award amount in `currency`'s smallest unit.
    pub amount: i128,
    pub currency: Symbol,
    /// #1091 — the immutable terms version this offer was issued against.
    pub terms_version: u32,
    /// #1090 — integrity commitment over the off-chain award terms.
    pub terms_hash: BytesN<32>,
    /// #1090 — optional reference to a milestone schedule (#1093) that
    /// splits this award; `None` for a single lump-sum award.
    pub milestone_schedule_id: Option<BytesN<32>>,
    pub offered_at: u64,
    /// #1090 — ledger timestamp after which acceptance is refused.
    pub acceptance_deadline: u64,
    pub status: AwardStatus,
    /// True while this award holds a budget reservation.
    pub reserved: bool,
    /// Total already disbursed against this award (tracked via
    /// `record_disbursement`); distinguishes pre-payment cancellation from
    /// post-payment termination in #1092.
    pub paid_amount: i128,
    /// Ledger timestamp of the terminal (or latest decision) transition.
    pub decided_at: u64,
    /// #1092 — machine-readable reason code supplied by the decider.
    pub reason_code: u32,
}

/// #1091 — the signed acceptance of the *exact* award terms. The terms
/// version and hash are copied from the offer at acceptance time, so a
/// later terms change can never retroactively alter what was agreed to.
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AgreementAcceptance {
    pub award_id: BytesN<32>,
    pub terms_version: u32,
    pub terms_hash: BytesN<32>,
    /// The address that signed — always the award's recipient.
    pub signer: Address,
    pub accepted_at: u64,
    /// Integrity commitment over the off-chain required declarations.
    pub declarations_hash: BytesN<32>,
}

#[contract]
pub struct ScholarshipAwardsContract;

#[contractimpl]
impl ScholarshipAwardsContract {
    /// Initialize the contract admin. Run once.
    pub fn initialize(env: Env, admin: Address) -> Result<(), ContractError> {
        if env.storage().instance().has(&DataKey::Admin) {
            return Err(ContractError::AlreadyInitialized);
        }
        admin.require_auth();
        env.storage().instance().set(&DataKey::Admin, &admin);
        Ok(())
    }

    fn require_admin(env: &Env, caller: &Address) -> Result<(), ContractError> {
        let admin: Address = env
            .storage()
            .instance()
            .get(&DataKey::Admin)
            .ok_or(ContractError::NotInitialized)?;
        if *caller != admin {
            return Err(ContractError::NotAdmin);
        }
        caller.require_auth();
        Ok(())
    }

    /// #1092 — the single policy table every status change is validated
    /// against. `Declined`, `Expired`, `Cancelled`, and `Terminated` are
    /// terminal — there is no transition out of, or between, them.
    fn is_legal_transition(from: AwardStatus, to: AwardStatus) -> bool {
        use AwardStatus::*;
        matches!(
            (from, to),
            (Offered, Accepted)
                | (Offered, Declined)
                | (Offered, Expired)
                | (Offered, Cancelled)
                | (Accepted, Cancelled)
                | (Accepted, Terminated)
        )
    }

    /// Store an award, extend its TTL, and return nothing. Split out so
    /// every mutation path applies the same TTL policy.
    fn put_award(env: &Env, award: &Award) {
        let key = DataKey::Award(award.id.clone());
        env.storage().persistent().set(&key, award);
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);
    }

    /// Read an award without extending TTL (internal helper).
    fn load_award(env: &Env, award_id: &BytesN<32>) -> Result<Award, ContractError> {
        env.storage()
            .persistent()
            .get(&DataKey::Award(award_id.clone()))
            .ok_or(ContractError::AwardNotFound)
    }

    /// Hold a reservation (one per active award) for a program.
    fn reserve(env: &Env, program_id: &BytesN<32>) -> Result<(), ContractError> {
        let key = DataKey::Reservation(program_id.clone());
        let current: u32 = env.storage().persistent().get(&key).unwrap_or(0);
        let next = current.checked_add(1).ok_or(ContractError::NoReservation)?;
        env.storage().persistent().set(&key, &next);
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);
        Ok(())
    }

    /// #1090 — release a program's reservation (on decline, expiry,
    /// cancellation, or termination). Checked so it can never underflow.
    fn release(env: &Env, program_id: &BytesN<32>) -> Result<(), ContractError> {
        let key = DataKey::Reservation(program_id.clone());
        let current: u32 = env.storage().persistent().get(&key).unwrap_or(0);
        let next = current.checked_sub(1).ok_or(ContractError::NoReservation)?;
        env.storage().persistent().set(&key, &next);
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);
        Ok(())
    }

    /// #1090 — clear the `(recipient, program_id)` uniqueness pointer so
    /// the applicant may later hold a fresh award for the same program.
    fn clear_active_award(env: &Env, recipient: &Address, program_id: &BytesN<32>) {
        env.storage()
            .persistent()
            .remove(&DataKey::ActiveAward(recipient.clone(), program_id.clone()));
    }

    // ── #1090 — award records and acceptance deadlines ───────────────────

    /// Admin-only: materialize an approved award. Fails if an award with
    /// this ID already exists, if the amount is not positive, if the
    /// acceptance deadline is not strictly in the future, or if the
    /// recipient already holds an active award for the same program.
    /// On success the award's budget reservation is held until the award
    /// reaches a terminal state.
    pub fn create_award(
        env: Env,
        admin: Address,
        award_id: BytesN<32>,
        program_id: BytesN<32>,
        recipient: Address,
        amount: i128,
        currency: Symbol,
        terms_version: u32,
        terms_hash: BytesN<32>,
        acceptance_deadline: u64,
        milestone_schedule_id: Option<BytesN<32>>,
    ) -> Result<(), ContractError> {
        Self::require_admin(&env, &admin)?;

        if amount <= 0 {
            return Err(ContractError::InvalidAmount);
        }
        let now = env.ledger().timestamp();
        if acceptance_deadline <= now {
            return Err(ContractError::InvalidDeadline);
        }

        let award_key = DataKey::Award(award_id.clone());
        if env.storage().persistent().has(&award_key) {
            return Err(ContractError::AwardAlreadyExists);
        }

        let active_key = DataKey::ActiveAward(recipient.clone(), program_id.clone());
        if env.storage().persistent().has(&active_key) {
            return Err(ContractError::ConflictingAward);
        }

        let award = Award {
            id: award_id.clone(),
            program_id: program_id.clone(),
            recipient: recipient.clone(),
            amount,
            currency,
            terms_version,
            terms_hash,
            milestone_schedule_id,
            offered_at: now,
            acceptance_deadline,
            status: AwardStatus::Offered,
            reserved: true,
            paid_amount: 0,
            decided_at: 0,
            reason_code: 0,
        };

        Self::put_award(&env, &award);

        env.storage().persistent().set(&active_key, &award_id);
        env.storage()
            .persistent()
            .extend_ttl(&active_key, RECORD_MIN_TTL, RECORD_MAX_TTL);

        Self::reserve(&env, &program_id)?;

        env.events().publish(
            (soroban_sdk::symbol_short!("AWCRT"),),
            (award_id, recipient, amount),
        );
        Ok(())
    }

    pub fn get_award(env: Env, award_id: BytesN<32>) -> Result<Award, ContractError> {
        let key = DataKey::Award(award_id);
        let award: Award = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(ContractError::AwardNotFound)?;
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);
        Ok(award)
    }

    /// #1090 — true iff this recipient currently holds an active
    /// (`Offered` or `Accepted`) award for this program.
    pub fn has_active_award(env: Env, recipient: Address, program_id: BytesN<32>) -> bool {
        env.storage()
            .persistent()
            .has(&DataKey::ActiveAward(recipient, program_id))
    }

    /// #1090 — authoritative count of awards currently holding a budget
    /// reservation for a program. Derived from storage, never cached.
    pub fn get_reservation(env: Env, program_id: BytesN<32>) -> u32 {
        env.storage()
            .persistent()
            .get(&DataKey::Reservation(program_id))
            .unwrap_or(0)
    }

    /// #1090/#1091 — true iff the offer's acceptance window has closed
    /// without a decision. Deterministic: a pure function of stored state
    /// and ledger time.
    pub fn is_acceptance_expired(env: Env, award_id: BytesN<32>) -> Result<bool, ContractError> {
        let award = Self::load_award(&env, &award_id)?;
        Ok(award.status == AwardStatus::Offered
            && env.ledger().timestamp() > award.acceptance_deadline)
    }

    // ── #1091 — signed agreement acceptance ─────────────────────────────

    /// The recipient signs the exact award terms. Requires the recipient's
    /// own authorization, refuses a closed window, and is only valid from
    /// `Offered`. The stored acceptance copies the offer's terms version
    /// and hash, so the agreement is bound to what was offered.
    pub fn accept_award(
        env: Env,
        recipient: Address,
        award_id: BytesN<32>,
        declarations_hash: BytesN<32>,
    ) -> Result<(), ContractError> {
        recipient.require_auth();

        let mut award = Self::load_award(&env, &award_id)?;
        if award.recipient != recipient {
            return Err(ContractError::NotRecipient);
        }
        if award.status != AwardStatus::Offered {
            return Err(ContractError::OfferNotActive);
        }

        let now = env.ledger().timestamp();
        if now > award.acceptance_deadline {
            return Err(ContractError::OfferExpired);
        }
        if !Self::is_legal_transition(award.status, AwardStatus::Accepted) {
            return Err(ContractError::InvalidTransition);
        }

        let acceptance = AgreementAcceptance {
            award_id: award_id.clone(),
            terms_version: award.terms_version,
            terms_hash: award.terms_hash.clone(),
            signer: recipient.clone(),
            accepted_at: now,
            declarations_hash,
        };
        let key = DataKey::Acceptance(award_id.clone());
        env.storage().persistent().set(&key, &acceptance);
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);

        award.status = AwardStatus::Accepted;
        award.decided_at = now;
        Self::put_award(&env, &award);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWACC"),),
            (award_id, recipient, now),
        );
        Ok(())
    }

    pub fn get_acceptance(
        env: Env,
        award_id: BytesN<32>,
    ) -> Result<AgreementAcceptance, ContractError> {
        let key = DataKey::Acceptance(award_id);
        let acceptance: AgreementAcceptance = env
            .storage()
            .persistent()
            .get(&key)
            .ok_or(ContractError::AcceptanceNotFound)?;
        env.storage()
            .persistent()
            .extend_ttl(&key, RECORD_MIN_TTL, RECORD_MAX_TTL);
        Ok(acceptance)
    }

    /// #1092 — true iff the award may still disburse. Deliberately false for
    /// `Declined`, `Expired`, `Cancelled`, `Terminated`, and for an
    /// `Accepted` award that is already fully paid.
    pub fn can_disburse(env: Env, award_id: BytesN<32>) -> Result<bool, ContractError> {
        let award = Self::load_award(&env, &award_id)?;
        Ok(award.status == AwardStatus::Accepted && award.paid_amount < award.amount)
    }

    // ── #1092 — cancellation and termination ────────────────────────────

    /// The recipient declines the offer. Terminal, releases the
    /// reservation, and clears the active-award pointer so the applicant
    /// can receive a different award for this program later.
    pub fn decline_award(
        env: Env,
        recipient: Address,
        award_id: BytesN<32>,
    ) -> Result<(), ContractError> {
        recipient.require_auth();

        let mut award = Self::load_award(&env, &award_id)?;
        if award.recipient != recipient {
            return Err(ContractError::NotRecipient);
        }
        if !Self::is_legal_transition(award.status, AwardStatus::Declined) {
            return Err(ContractError::InvalidTransition);
        }

        award.status = AwardStatus::Declined;
        award.decided_at = env.ledger().timestamp();
        award.reserved = false;
        Self::put_award(&env, &award);
        Self::release(&env, &award.program_id)?;
        Self::clear_active_award(&env, &award.recipient, &award.program_id);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWDEC"),),
            (award_id, recipient),
        );
        Ok(())
    }

    /// #1090 — permissionless expiry: after the acceptance deadline has
    /// passed, anyone may move an unanswered `Offered` award to `Expired`,
    /// releasing its reservation. Cannot be called before the deadline, and
    /// has no effect on a decided award.
    pub fn expire_award(env: Env, award_id: BytesN<32>) -> Result<(), ContractError> {
        let mut award = Self::load_award(&env, &award_id)?;
        if award.status != AwardStatus::Offered {
            return Err(ContractError::InvalidTransition);
        }
        if env.ledger().timestamp() <= award.acceptance_deadline {
            return Err(ContractError::OfferNotExpired);
        }

        award.status = AwardStatus::Expired;
        award.decided_at = env.ledger().timestamp();
        award.reserved = false;
        Self::put_award(&env, &award);
        Self::release(&env, &award.program_id)?;
        Self::clear_active_award(&env, &award.recipient, &award.program_id);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWEXP"),),
            (award_id, award.recipient),
        );
        Ok(())
    }

    /// #1092 — pre-payment cancellation. Allowed from `Offered` or
    /// `Accepted` only while nothing has been paid; once any disbursement
    /// exists the award must be *terminated* instead. Releases the
    /// reservation and records the reason code and deciding authority.
    pub fn cancel_award(
        env: Env,
        admin: Address,
        award_id: BytesN<32>,
        reason_code: u32,
    ) -> Result<(), ContractError> {
        Self::require_admin(&env, &admin)?;

        let mut award = Self::load_award(&env, &award_id)?;
        if award.paid_amount > 0 {
            return Err(ContractError::PaymentAlreadyMade);
        }
        if !Self::is_legal_transition(award.status, AwardStatus::Cancelled) {
            return Err(ContractError::InvalidTransition);
        }

        award.status = AwardStatus::Cancelled;
        award.decided_at = env.ledger().timestamp();
        award.reason_code = reason_code;
        award.reserved = false;
        Self::put_award(&env, &award);
        Self::release(&env, &award.program_id)?;
        Self::clear_active_award(&env, &award.recipient, &award.program_id);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWCAN"),),
            (award_id, award.recipient, reason_code),
        );
        Ok(())
    }

    /// #1092 — post-payment termination. Requires an `Accepted` award with
    /// at least one recorded disbursement. Stops all future payments and
    /// records any recovery separately from the amount already paid.
    pub fn terminate_award(
        env: Env,
        admin: Address,
        award_id: BytesN<32>,
        reason_code: u32,
        recovery_amount: i128,
    ) -> Result<(), ContractError> {
        Self::require_admin(&env, &admin)?;

        let mut award = Self::load_award(&env, &award_id)?;
        if award.paid_amount == 0 {
            return Err(ContractError::NoPaymentMade);
        }
        if recovery_amount < 0 || recovery_amount > award.paid_amount {
            return Err(ContractError::RecoveryExceedsPaid);
        }
        if !Self::is_legal_transition(award.status, AwardStatus::Terminated) {
            return Err(ContractError::InvalidTransition);
        }

        award.status = AwardStatus::Terminated;
        award.decided_at = env.ledger().timestamp();
        award.reason_code = reason_code;
        award.reserved = false;
        Self::put_award(&env, &award);

        // Recoveries are tracked in their own record — never folded into
        // `paid_amount`, so the two are always independently auditable.
        let rkey = DataKey::Recovery(award_id.clone());
        env.storage().persistent().set(&rkey, &recovery_amount);
        env.storage()
            .persistent()
            .extend_ttl(&rkey, RECORD_MIN_TTL, RECORD_MAX_TTL);

        Self::release(&env, &award.program_id)?;
        Self::clear_active_award(&env, &award.recipient, &award.program_id);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWTRM"),),
            (award_id, award.recipient, recovery_amount),
        );
        Ok(())
    }

    pub fn get_recovery(env: Env, award_id: BytesN<32>) -> i128 {
        env.storage()
            .persistent()
            .get(&DataKey::Recovery(award_id))
            .unwrap_or(0)
    }

    /// Record that `amount` was disbursed against an accepted award
    /// elsewhere. Kept as accounting only — this contract does not move
    /// funds. Refuses any award that is not `Accepted`, and can never push
    /// the paid total past the award amount, so a terminated award's
    /// `AwardNotDisburseable` error is what "future payments stop" means
    /// on-chain.
    pub fn record_disbursement(
        env: Env,
        admin: Address,
        award_id: BytesN<32>,
        amount: i128,
    ) -> Result<(), ContractError> {
        Self::require_admin(&env, &admin)?;

        if amount <= 0 {
            return Err(ContractError::InvalidAmount);
        }
        let mut award = Self::load_award(&env, &award_id)?;
        if award.status != AwardStatus::Accepted {
            return Err(ContractError::AwardNotDisburseable);
        }
        let new_paid = award
            .paid_amount
            .checked_add(amount)
            .ok_or(ContractError::DisbursementExceedsAward)?;
        if new_paid > award.amount {
            return Err(ContractError::DisbursementExceedsAward);
        }
        award.paid_amount = new_paid;
        Self::put_award(&env, &award);

        env.events().publish(
            (soroban_sdk::symbol_short!("AWDIS"),),
            (award_id, amount, new_paid),
        );
        Ok(())
    }

    pub fn version(_env: Env) -> u32 {
        CONTRACT_VERSION
    }
}

#[cfg(test)]
mod tests;
