#!/usr/bin/env bash
# scripts/deploy-testnet.sh
#
# Deploy all ChainVerse contracts to Stellar testnet and write
# contract addresses to deployments/testnet.json and .env.testnet.
#
# Usage:
#   cp .env.testnet.example .env.testnet   # set STELLAR_IDENTITY etc.
#   ./scripts/deploy-testnet.sh
set -euo pipefail

NETWORK="${STELLAR_NETWORK:-testnet}"
STELLAR_IDENTITY="${STELLAR_IDENTITY:-deployer}"
CONTRACTS_DIR="${CONTRACTS_DIR:-contracts}"

# ---------------------------------------------------------------------------
# Pre-flight: validate working directory
# ---------------------------------------------------------------------------
if [ ! -d "$CONTRACTS_DIR" ]; then
  echo "ERROR: contracts directory not found: $CONTRACTS_DIR" >&2
  exit 1
fi

echo "Building all contracts in $CONTRACTS_DIR..."
cargo build --manifest-path "$CONTRACTS_DIR/Cargo.toml" \
  --target wasm32-unknown-unknown --release

# ---------------------------------------------------------------------------
# Helper: deploy a single WASM and return its contract ID
# ---------------------------------------------------------------------------
deploy() {
  local crate_name=$1
  local wasm_name=${2:-$crate_name}
  local wasm_path="$CONTRACTS_DIR/target/wasm32-unknown-unknown/release/${wasm_name}.wasm"

  if [ ! -f "$wasm_path" ]; then
    echo "ERROR: WASM artifact not found: $wasm_path" >&2
    exit 1
  fi

  echo "Deploying $crate_name..."
  stellar contract deploy \
    --wasm "$wasm_path" \
    --source "$STELLAR_IDENTITY" \
    --network "$NETWORK"
}

# ---------------------------------------------------------------------------
# Deploy all platform contracts (order matters for cross-contract refs)
# ---------------------------------------------------------------------------
CHV_TOKEN_CONTRACT_ID=$(deploy chv_token chv_token)
CERTIFICATES_CONTRACT_ID=$(deploy certificates certificates)
ESCROW_CONTRACT_ID=$(deploy escrow escrow)
ESCROW_VAULT_CONTRACT_ID=$(deploy escrow-vault escrow_vault)
CHAINVERSE_CORE_CONTRACT_ID=$(deploy chainverse-core chainverse_core)
REWARD_CONTRACT_ID=$(deploy reward reward)
STAKING_CONTRACT_ID=$(deploy staking staking)
PAYOUT_AUTOMATION_CONTRACT_ID=$(deploy payout-automation payout_automation)
COURSE_REGISTRY_CONTRACT_ID=$(deploy course_registry course_registry)

# ---------------------------------------------------------------------------
# Atomic write: deployment manifest (JSON)
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "deployments/testnet.json")"
TEMP_JSON="deployments/testnet.json.tmp.$$"
cat > "$TEMP_JSON" <<EOJSON
{
  "network": "$NETWORK",
  "rpc_url": "https://soroban-testnet.stellar.org",
  "passphrase": "Test SDF Network ; September 2015",
  "deployed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "deployer": "$STELLAR_IDENTITY",
  "contracts": {
    "chv_token": "$CHV_TOKEN_CONTRACT_ID",
    "certificates": "$CERTIFICATES_CONTRACT_ID",
    "escrow": "$ESCROW_CONTRACT_ID",
    "escrow_vault": "$ESCROW_VAULT_CONTRACT_ID",
    "chainverse_core": "$CHAINVERSE_CORE_CONTRACT_ID",
    "reward": "$REWARD_CONTRACT_ID",
    "staking": "$STAKING_CONTRACT_ID",
    "payout_automation": "$PAYOUT_AUTOMATION_CONTRACT_ID",
    "course_registry": "$COURSE_REGISTRY_CONTRACT_ID"
  }
}
EOJSON
mv "$TEMP_JSON" "deployments/testnet.json"
echo "Deployment manifest written to deployments/testnet.json"

# ---------------------------------------------------------------------------
# Atomic write: environment file
# ---------------------------------------------------------------------------
TEMP_ENV=".env.testnet.tmp.$$"
cat > "$TEMP_ENV" <<EOENV
# Auto-generated by scripts/deploy-testnet.sh — do not edit manually.
STELLAR_NETWORK=$NETWORK
STELLAR_IDENTITY=$STELLAR_IDENTITY
CHV_TOKEN_CONTRACT_ID=$CHV_TOKEN_CONTRACT_ID
CERTIFICATES_CONTRACT_ID=$CERTIFICATES_CONTRACT_ID
ESCROW_CONTRACT_ID=$ESCROW_CONTRACT_ID
ESCROW_VAULT_CONTRACT_ID=$ESCROW_VAULT_CONTRACT_ID
CHAINVERSE_CORE_CONTRACT_ID=$CHAINVERSE_CORE_CONTRACT_ID
REWARD_CONTRACT_ID=$REWARD_CONTRACT_ID
STAKING_CONTRACT_ID=$STAKING_CONTRACT_ID
PAYOUT_AUTOMATION_CONTRACT_ID=$PAYOUT_AUTOMATION_CONTRACT_ID
COURSE_REGISTRY_CONTRACT_ID=$COURSE_REGISTRY_CONTRACT_ID
EOENV
mv "$TEMP_ENV" ".env.testnet"
echo "Environment written to .env.testnet"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "=== Deployment complete ==="
echo "CHV Token:            $CHV_TOKEN_CONTRACT_ID"
echo "Certificates:         $CERTIFICATES_CONTRACT_ID"
echo "Escrow:               $ESCROW_CONTRACT_ID"
echo "Escrow Vault:         $ESCROW_VAULT_CONTRACT_ID"
echo "ChainVerse Core:      $CHAINVERSE_CORE_CONTRACT_ID"
echo "Reward:               $REWARD_CONTRACT_ID"
echo "Staking:              $STAKING_CONTRACT_ID"
echo "Payout Automation:    $PAYOUT_AUTOMATION_CONTRACT_ID"
echo "Course Registry:      $COURSE_REGISTRY_CONTRACT_ID"
