#!/bin/bash
set -e

NETWORK="${1:-testnet}"
SOURCE="${2:-deployer}"
CONTRACT_NAME="$3"
NEW_WASM="$4"

if [ -z "$CONTRACT_NAME" ] || [ -z "$NEW_WASM" ]; then
  echo "Usage: $0 [network] [source] <contract-name> <new-wasm-path>"
  echo ""
  echo "Examples:"
  echo "  $0 testnet deployer chv_token ./contracts/target/wasm32-unknown-unknown/release/chv_token.wasm"
  echo "  $0 mainnet admin escrow ./contracts/target/wasm32-unknown-unknown/release/escrow.wasm"
  exit 1
fi

RPC_URL="https://soroban-${NETWORK}.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
if [ "$NETWORK" = "mainnet" ]; then
  PASSPHRASE="Public Global Stellar Network ; September 2015"
  RPC_URL="https://soroban-rpc.mainnet.stellar.org"
fi

DEPLOYMENTS_FILE="deployments/${NETWORK}.json"

if [ ! -f "$DEPLOYMENTS_FILE" ]; then
  echo "Error: $DEPLOYMENTS_FILE not found. Run deploy-testnet.sh first."
  exit 1
fi

CONTRACT_ID=$(python3 -c "
import json
with open('$DEPLOYMENTS_FILE') as f:
    data = json.load(f)
print(data.get('contracts', {}).get('$CONTRACT_NAME', ''))
")

if [ -z "$CONTRACT_ID" ]; then
  echo "Error: Contract '$CONTRACT_NAME' not found in $DEPLOYMENTS_FILE"
  exit 1
fi

echo "Upgrading $CONTRACT_NAME ($CONTRACT_ID) to $NEW_WASM on $NETWORK..."

if [ ! -f "$NEW_WASM" ]; then
  echo "Error: WASM file $NEW_WASM not found"
  exit 1
fi

# ---------------------------------------------------------------------------
# Pre-upgrade validation
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "Running pre-upgrade compatibility checks..."
if ! "$SCRIPT_DIR/validate-upgrade.sh" "$NETWORK" "$SOURCE" "$CONTRACT_NAME" "$NEW_WASM"; then
  echo ""
  echo "Error: Pre-upgrade validation failed. Upgrade of $CONTRACT_NAME aborted."
  echo "       Review the validation output above and fix the issues before retrying."
  exit 1
fi
echo ""

# ---------------------------------------------------------------------------
# Rollback reference snapshot
# ---------------------------------------------------------------------------
ROLLBACK_DIR="deployments/rollback-refs"
mkdir -p "$ROLLBACK_DIR"

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
ROLLBACK_FILE="${ROLLBACK_DIR}/${NETWORK}-${CONTRACT_NAME}-${TIMESTAMP}.txt"
WASM_HASH=$(sha256sum "$NEW_WASM" | awk '{print $1}')

cat > "$ROLLBACK_FILE" <<EOF
# Rollback reference — recorded before upgrade
# Generated by scripts/upgrade-contract.sh at ${TIMESTAMP}

network:       ${NETWORK}
contract_name: ${CONTRACT_NAME}
contract_id:   ${CONTRACT_ID}
new_wasm:      ${NEW_WASM}
sha256:        ${WASM_HASH}
upgraded_by:   ${SOURCE}
timestamp:     ${TIMESTAMP}
EOF

echo "Rollback reference saved → $ROLLBACK_FILE"
echo "  sha256: $WASM_HASH"
echo ""

# ---------------------------------------------------------------------------
# Perform the upgrade
# ---------------------------------------------------------------------------
stellar contract upgrade \
  --contract-id "$CONTRACT_ID" \
  --wasm "$NEW_WASM" \
  --source "$SOURCE" \
  --network "$NETWORK"

echo "Upgrade of $CONTRACT_NAME completed successfully."
